version: "3"

services:
  database:
    image: mysql
    restart: always
    environment:
      - MYSEL_DATABASE=db
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    ports:
      - "3306:3306"